# Generated by Django 5.2 on 2025-04-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_1', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_2', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_3', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_4', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_5', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_6', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_7', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_8', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_9', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_10', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_11', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_12', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_13', models.CharField(blank=True, max_length=255, null=True)),
                ('benefit_14', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_1', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_2', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_3', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_4', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_5', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_6', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_7', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_8', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_9', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_10', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_11', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_12', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_13', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_14', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=255)),
                ('jobCategory', models.CharField(blank=True, max_length=255, null=True)),
                ('jobIndustry', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('vacancy', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('jobLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('jobType', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(max_length=500)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.benefit')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.skill')),
            ],
            options={
                'verbose_name': 'Job Data',
                'verbose_name_plural': 'Job Data',
                'ordering': ['-datePosted'],
            },
        ),
    ]
