# Generated by Django 5.2 on 2025-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedHTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('html_content', models.TextField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('processing_success', models.BooleanField(default=False)),
                ('source_domain', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Scraped HTML',
                'verbose_name_plural': 'Scraped HTMLs',
                'indexes': [models.Index(fields=['url'], name='scraper_scr_url_9c54ed_idx'), models.Index(fields=['scraped_at'], name='scraper_scr_scraped_f52bdd_idx'), models.Index(fields=['processing_success'], name='scraper_scr_process_5cabfb_idx')],
            },
        ),
    ]
